apiVersion: v1
kind: Service
metadata:
  name: mycmdb
  namespace: ops-tools
  labels:
    app: mycmdb
spec:
  selector:
    app: mycmdb
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 9090
